name: themar_app_amit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  carousel_slider: ^5.0.0
  flutter_bloc: ^9.0.0
  flutter_widget_from_html_core: ^0.16.0
  get_it: ^8.0.3
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.10.1
  maps_launcher: ^3.0.0+1
  geocoding: ^3.0.0
  chart_sparkline: ^1.1.1
  circular_countdown_timer: ^0.2.4
  easy_localization: ^3.0.7+1
  animated_notch_bottom_bar: ^1.0.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.2
  quick_log: ^5.5.3
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svg/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

